export const websitePackage = [
  {
    id: 1,
    buttonTitle: "Get Started",
    packageHeading: "Basic Website Package",
    packageDescription: "Cost Effective Package for your business",
    duration: 30,
    currentPrice: 200,
    originalPrice: 400,
    features: [
      "1-Page Website",
      "Customized Design (basic)",
      "WordPress",
      "Contact Form",
      "1 Banner Design (basic)",
      "3 Revisions",
      "Dedicated Project Manager",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    id: 2,
    packageHeading: "Standard Website Package",
    packageDescription: "Cost Effective Package for your business",
    duration: 30,
    currentPrice: 400,
    originalPrice: 800,
    buttonTitle: "Get Started",
    features: [
      "Up to 3-Page Website",
      "Customized Design (Standard)",
      "WordPress",
      "Mobile Responsive",
      "Hover Effects",
      "Stock Photos",
      "Contact Form",
      "6 Revisions",
      "Complete Design and Development",
      "Dedicated Project Manager",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    id: 3,
    packageHeading: "Professional Website Package",
    packageDescription: "Cost Effective Package for your business",
    duration: 30,
    currentPrice: 750,
    originalPrice: 1500,
    buttonTitle: "Get Started",
    features: [
      "Up to 5-Page Website",
      "Customized Design (Professional)",
      "WordPress",
      "CMS (Content Management System)",
      "5 Banner Design (Professional)",
      "Sliding Banners",
      "Hover Effects",
      "Mobile Responsive",
      "Stock Photos",
      "Contact Form",
      "Search Engine Submission",
      "9 Revisions",
      "Complete Design and Development",
      "Dedicated Project Manager",
      "100% Satisfaction Guarantee",
      "100% Ownership Rights",
    ],
  },
  {
    id: 4,
    packageHeading: "Website Identity Kit",
    packageDescription: "Cost Effective Package for your business",
    duration: 30,
    currentPrice: 1400,
    originalPrice: 2800,
    buttonTitle: "Get Started",
    features: [
      "Up to 7-Page Website (Unique)",
      "Custom WordPress Development",
      "Stock Images",
      "7 Banner Designs (Custom)",
      "Sliding Banners",
      "Hover Effects",
      "Content Management System",
      "Online Appointment/Booking/Scheduling Integration",
      "Search Engine Submission",
      "12 Revisions",
      "Complete Design and Development",
      "Interactive Hover Effects",
      "18 Revisions",
      "Content Management System (WordPress)",
      "Online Appointment/Booking/Scheduling Integration (Optional)",
      "Online Payment Integration (Optional)",
      "Custom Contact Form (Optional)",
      "Newsletter Sign up (Optional)",
      "Social Media Integration",
      "Search Bar",
      "Google Friendly Sitemap",
      "Dedicated Project Manager",
      "100% Satisfaction Guarantee",
      "100% Ownership Rights",
    ],
  },
  {
    id: 5,
    packageHeading: "Exclusive Web Package",
    packageDescription: "Cost Effective Package for your business",
    duration: 30,
    currentPrice: 1750,
    originalPrice: 3500,
    buttonTitle: "Get Started",
    features: [
      "Up to 10-Page Website (Unique)",
      "Custom, Dynamic, and Interactive Design",
      "Custom WordPress Development",
      "Captivating Sliding Banners",
      "Stock Images",
      "10 Banner Design (Custom)",
      "Interactive Hover Effects",
      "15 Revisions",
      "Content Management System (WordPress)",
      "Online Appointment/Booking/Scheduling Integration",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "Complete Design and Development",
      "Dedicated Project Manager",
      "100% Satisfaction Guarantee",
      "100% Ownership Rights",
    ],
  },
  {
    id: 6,
    packageHeading: "Professional Website Package",
    packageDescription: "Cost Effective Package for your business",
    duration: 30,
    currentPrice: 3200,
    originalPrice: 6400,
    buttonTitle: "Get Started",
    features: [
      "10–20 Page Website (Unique)",
      "Custom, Dynamic, and High-end Design",
      "Custom WordPress Development",
      "Attractive Sliding Banners",
      "Up to 20 Custom Banner Designs",
      "Stock Images",
      "Interactive Hover Effects",
      "18 Revisions",
      "Content Management System (WordPress)",
      "Online Appointment/Booking/Scheduling Integration (Optional)",
      "Online Payment Integration (Optional)",
      "Custom Contact Form (Optional)",
      "Newsletter Sign-up (Optional)",
      "Social Media Integration",
      "Search Bar",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "Complete Design and Development",
      "Dedicated Project Manager",
      "100% Satisfaction Guarantee",
      "100% Ownership Rights",
    ],
  },
  {
    id: 7,
    buttonTitle: "Get Started",
    packageHeading: "Custom Website Package",
    packageDescription: "Cost Effective Package for your business",
    duration: null,
    currentPrice: null,
    originalPrice: null,
    features: ["Custom PHP Website", "Web Application", "Custom Web Portal"],
  },
];
export const brandingPackages = [
  {
    id: 1,
    packageHeading: "Business Card Design",
    packageDescription: "Professional custom business card",
    currentPrice: 25.99,
    originalPrice: 50.99,
    buttonTitle: "Get Started",
    features: [
      "1 Business Card",
      "UNLIMITED Revisions",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
    ],
  },
  {
    id: 2,
    packageHeading: "Complete Stationery",
    packageDescription: "Full branding stationery set",
    currentPrice: 99.99,
    originalPrice: 199.99,
    buttonTitle: "Get Started",
    features: [
      "5 Business Cards",
      "5 Letterheads",
      "5 Envelopes",
      "100% Unique Design Guarantee",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    id: 3,
    packageHeading: "Tri-Fold Brochure Design",
    packageDescription: "Custom tri-fold brochure ready for print",
    currentPrice: 199.99,
    originalPrice: 399.99,
    buttonTitle: "Get Started",
    features: [
      "Tri-Fold Brochure Design",
      "3 Stock Images",
      "Print Ready Formats",
      "Unlimited Revisions",
      "100% Unique Design Guarantee",
      "100% Satisfaction Guarantee",
    ],
  },
];


export const socialMediaPackage = [
  {
    id: 1,
    packageHeading: "Social Media Presence",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 125,
    originalPrice: 250,
    buttonTitle: "Buy Now",
    features: [
      "Social Business Account Creation (Any 3)",
      "Cover Photo Design",
      "Profile Picture Design",
      "Welcome Post Design",
    ],
  },
  {
    id: 2,
    packageHeading: "Essential Monthly Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 400,
    originalPrice: 800,
    buttonTitle: "Buy Now",
    features: [
      "2 Posting Per Week, Each Network (Instagram and Facebook)",
      "Content Generation",
      "Post Design",
      "Business Page Optimization",
      "Social Media Calendar",
      "Monthly Progress Report",
      "Paid Boosting (Additional Charges according to the budget)",
    ],
  },
  {
    id: 3,
    packageHeading: "Classic Monthly Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 800,
    originalPrice: 1600,
    buttonTitle: "Buy Now",
    features: [
      "5 Posting Per Week, Each Network (Facebook, Instagram, Twitter)",
      "Business Page Optimization",
      "Content Generation",
      "Post Design",
      "Social Media Calendar",
      "Spam Monitoring",
      "Comment Moderation",
      "Reputation Management",
      "Monthly Progress Report",
      "Paid Boosting (Additional Charges according to the budget)",
    ],
  },
  {
    id: 4,
    packageHeading: "Advanced Monthly Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 1200,
    originalPrice: 2400,
    buttonTitle: "Buy Now",
    features: [
      "6 Posting Per Week, Each Network (Instagram, Facebook, Twitter, Pinterest)",
      "45 Sec Video Animation",
      "Content Generation",
      "Social Account Setup",
      "Business Page Optimization",
      "Banner and Profile Picture Design",
      "Social Media Calendar",
      "Social Media Strategy",
      "Facebook Likes Campaign",
      "Comment Moderation",
      "Spam Monitoring",
      "Reputation Management",
      "Paid Boosting (Additional Charges according to the budget)",
    ],
  },
  {
    id: 5,
    packageHeading: "Exlusive Monthly Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 3000,
    originalPrice: 6000,
    buttonTitle: "Buy Now",
    features: [
      "30 Post Per Month, Each Network (Instagram, Facebook, Twitter, Pinterest, and LinkedIn)",
      "4 20 Seconds Video Animation",
      "Custom Post Design",
      "Content Generation",
      "5 Boosted Posts",
      "Social Account Setup",
      "Business Page Optimization",
      "Banner and Profile Picture Design",
      "Social Media Calendar",
      "Social Media Strategy",
      "Social Media Audit",
      "Brand Analysis",
      "Facebook Likes Campaign",
      "Comment Moderation",
      "Spam Monitoring",
      "Reputation Management",
      "Daily Monitoring of Boosted Posts",
      "Monthly Progress Report",
      "Paid Boosting (Additional Charges according to the budget)",
    ],
  },
];

export const mobileAppPackage = [
  {
    id: 1,
    packageHeading: "Hybrid Application",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: null,
    originalPrice: null,
    buttonTitle: "Get a quote",
    features: ["Let's Discuss"],
  },
  {
    id: 2,
    packageHeading: "IOS Application Development",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: null,
    originalPrice: null,
    buttonTitle: "Get a quote",
    features: ["Let's Discuss"],
  },
  {
    id: 3,
    packageHeading: "Android Application",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: null,
    originalPrice: null,
    buttonTitle: "Get a quote",
    features: ["Let's Discuss"],
  },
];

export const logoPackage = [
  {
    id: 1,
    packageHeading: "Startup Logo Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 79,
    originalPrice: 79,
    buttonTitle: "Get Started",
    features: [
      "3 Logo Design Concepts",
      "2 Dedicated Designer",
      "6 Revisions",
      "24 Hours Turn Around Time",
      "Final Files (JPEG, PNG, PDF)",
      "3 Revisions",
      "Dedicated Project Manager",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    id: 2,
    packageHeading: "Silver Logo Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 150,
    originalPrice: 150,
    buttonTitle: "Get Started",
    features: [
      "5 Logo Design Concept",
      "3 Dedicated Designers",
      "10 Revisions",
      "24 Hours Turn Around Time",
      "Final Files (JPEG, PNG, PDF, PSD)",
      "Dedicated Project Manager",
      "100% Unique Concepts",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    id: 3,
    packageHeading: "Gold Logo Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 250,
    originalPrice: 250,
    buttonTitle: "Get Started",
    features: [
      "8 Logo Design Concepts",
      "Business Card Design",
      "3 Dedicated Designers",
      "Unlimited",
      "24-48 hours Turn Around Time",
      "Final Files (AI, PSD, EPS, JPEG, PNG, PDF)",
      "Dedicated Project Manager",
      "100% Unique Concepts",
      "100% Approval Assurance",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    id: 4,
    packageHeading: "Platinum Logo Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 400,
    originalPrice: 400,
    buttonTitle: "Get Started",
    features: [
      "10 Logo Design Concepts",
      "Stationery Design (Business card design, Letterhead Design, Envelope Design)",
      "7 Dedicated Designers",
      "Unlimited Revisions",
      "48-72 Hours Turn Around Time",
      "Final Files (AI, PSD, EPS, JPEG, PNG, PDF, SVG)",
      "Dedicated Project Manager",
      "100% Unique Concepts",
      "100% Approval Assurance",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    id: 5,
    packageHeading: "Ultimate Logo Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 479,
    originalPrice: 479,
    buttonTitle: "Get Started",
    features: [
      "12 Logo Design Concepts",
      "Stationery Design (Business card design, Letterhead Design, Envelope Design)",
      "Flyer Design",
      "Free Icon Design",
      "8 Dedicated Designers",
      "Unlimited Revisions",
      "48-72 Hours Turn Around Time",
      "Final Files (AI, PSD, EPS, JPEG, PNG, PDF, SVG)",
      "Dedicated Project Manager",
      "100% Unique Concepts",
      "100% Approval Assurance",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    id: 6,
    packageHeading: "Custom Logo Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: null,
    originalPrice: null,
    buttonTitle: "Get a quote",
    features: ["Illustrative Logo", "Animated Logo", "2D Logo", "3D Logo"],
  },
];

export const seoPackage = [
  {
    id: 1,
    packageHeading: "SEO Essential",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 250,
    originalPrice: 500,
    buttonTitle: "Get Started",
    features: [
      "5 Keywords",
      "Off-page Optimization",
      "Link Building",
      "Social Bookmarking",
      "Guaranteed Ranking on Google",
      "Basic Analytical Report",
      "Dedicated Project Manager",
    ],
  },
  {
    id: 2,
    packageHeading: "SEO Standard",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 500,
    originalPrice: 1000,
    buttonTitle: "Get Started",
    features: [
      "10 Keywords",
      "Off-page Optimization",
      "On-page Optimization",
      "Link Building Social Bookmarking",
      "Guaranteed Ranking on Google",
      "Comprehensive Analytical Report",
      "Dedicated Project Manager",
    ],
  },
  {
    id: 3,
    packageHeading: "SEO Classic",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 700,
    originalPrice: 1400,
    buttonTitle: "Get Started",
    features: [
      "20 Keywords",
      "Off-page Optimization",
      "On-page Optimization",
      "Link Building",
      "Social Bookmarking",
      "Guaranteed Ranking on Google",
      "Comprehensive Analytical Report",
      "Dedicated Project Manager",
    ],
  },
  {
    id: 4,
    packageHeading: "SEO Exclusive",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 1300,
    originalPrice: 2600,
    buttonTitle: "Get Started",
    features: [
      "30 keywords",
      "Off-page Optimization",
      "On-page Optimization",
      "Technical SEO",
      "Website Audit",
      "Link Building",
      "Social Bookmarking",
      "Website Performance Enhancement",
      "Comprehensive Analytical Report",
      "Dedicated Project Manager",
    ],
  },
];

export const ecommercePackage = [
  {
    id: 1,
    packageHeading: "E-Commerce Essential Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 649,
    originalPrice: 1000,
    buttonTitle: "Get Started",
    features: [
      "E-Commerce Website Design and Development",
      "Basic Design",
      "3 Banner Designs",
      "4 Stock Photos",
      "Hover Effects",
      "Up to 70 Products",
      "Up to 3 Categories",
      "Content/Inventory Management System",
      "Shopping Cart Integration",
      "Payment Module Integration",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    id: 2,
    packageHeading: "E-commerce Standard Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 849,
    originalPrice: 1600,
    buttonTitle: "Get Started",
    features: [
      "E-Commerce Website Design and Development",
      "Standard Design",
      "5 Banner Designs",
      "Stock Photos",
      "08 Revisions",
      "Hover Effects",
      "Up to 100 Products",
      "Up to 5 Categories",
      "Content/Inventory Management System",
      "Shopping Cart Integration",
      "Easy Product Search Bar",
      "Payment Module Integration (2)",
      "Direct Checkout",
      "Search Engine Submission",
      "Social Media Pages Integration",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    id: 3,
    packageHeading: "E-Commerce Professional Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 1179,
    originalPrice: 2600,
    buttonTitle: "Get Started",
    features: [
      "E-commerce Website Design and Development",
      "Professional Design",
      "10 Banner Designs",
      "Stock Photos",
      "12 Revisions",
      "Special Hover Effects",
      "Interactive Sliding Banners",
      "Up to 100 Products",
      "Up to 10 Categories",
      "Content/Inventory Management System",
      "Easy Product Search Bar",
      "Shopping Cart Integration",
      "Direct Checkout",
      "Shipping Calculator Integration",
      "Wishlist",
      "Search Engine Submission",
      "Social Media Pages Integration",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    id: 4,
    packageHeading: "E-Commerce identity kit",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 1999,
    originalPrice: 4400,
    buttonTitle: "Get Started",
    features: [
      "E-commerce Website Design and Development",
      "Custom WordPress Development",
      "Modern, Interactive, and Unique Design",
      "12 Banner Designs (Custom)",
      "Interactive Sliding Banners",
      "Special Hover Effects",
      "Stock Photos",
      "25 Revisions",
      "Up to 450 products",
      "Up to 30 Categories",
      "Product Review and Ratings",
      "Content/Inventory Management System",
      "Mobile Responsive",
      "Easy Product Search Bar",
      "Shopping Cart Integration",
      "Direct Checkout",
      "Sign up Checkout",
      "Tax Calculator Integration",
      "Shipping Calculator Integration",
      "Wishlist",
      "Bulk Import/Export Order",
      "Search Engine Submission",
      "SEO Friendly",
      "Social Media Pages Integration",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    id: 5,
    packageHeading: "E-commerce Exclusive Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 3200,
    originalPrice: 6400,
    buttonTitle: "Get Started",
    features: [
      "E-Commerce Website Design and Development",
      "Customized Tailor-Made Design",
      "Professional, Modern, and Unique Design",
      "User-friendly Navigation",
      "20 Banner Designs",
      "Sliding Banner",
      "20 Stock Photos",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Content/Inventory Management System",
      "Mobile Responsive",
      "Up to 700 Products",
      "Up to 70 Categories",
      "Product Reviews & Ratings Product Summary Reports (Out of stock / Most Sold / Lowest sale etc) By Date",
      "Multiple Filtrations Option",
      "Product View with Multiple Views",
      "Product Detail with Similar Product Range",
      "Discounted Products Showcase",
      "New Arrival Products Showcase",
      "Discount Coupons",
      "Easy Product Search Bar",
      "Payment Module Integration",
      "Direct Checkout",
      "Sign up Checkout",
      "Tax Calculator Integration",
      "Shipping Calculator Integration",
      "Wishlist",
      "Import/Export Order",
      "Bulk Import/Export Order Information",
      "Live Chat Integration",
      "Social Media Pages Integration",
      "Blog Page",
      "Sitemap",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100 Satisfaction Guarantee",
    ],
  },
];

export const uiDesignPackages = [
  {
    id: 1,
    buttonTitle: "Get Started",
    packageHeading: "Basic UI Design Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 1500,
    originalPrice: 3000,
    features: [
      "Homepage design",
      "Up to 5 additional pages",
      "Basic layout and design elements",
      "Typography",
      "Color scheme",
    ],
  },
  {
    id: 2,
    buttonTitle: "Get Started",
    packageHeading: "Advanced UI Design Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 2000,
    originalPrice: 4000,
    features: [
      "Homepage design",
      "Up to 10 additional pages",
      "More complex design elements",
      "Illustrations",
      "Animations",
      "Interactive features",
      "Iconography and graphic design",
    ],
  },
  {
    id: 3,
    buttonTitle: "Get Started",
    packageHeading: "E-Commerce Design Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 3000,
    originalPrice: 6000,
    features: [
      "Homepage design",
      "Up to 20 additional pages",
      "Shopping cart design",
      "Product page design",
      "Checkout process design",
      "Custom graphic design for promotional materials",
    ],
  },
  {
    id: 4,
    buttonTitle: "Get Started",
    packageHeading: "Responsive Design Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 3500,
    originalPrice: 7000,
    features: [
      "Homepage design",
      "Up to 10 additional pages",
      "Optimized for all devices, including desktops, tablets, and mobile phones",
      "Touch-friendly interfaces and larger fonts for easier reading on smaller screens",
    ],
  },
  {
    id: 5,
    buttonTitle: "Get Started",
    packageHeading: "Custom Design Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 6000,
    originalPrice: 12000,
    features: [
      "Completely tailored to the client’s specific needs",
      "Can include any combination of design elements, from basic to advanced",
      "Customizable for any type of website or web application",
      "Illustrations",
      "Animations",
      "Interactive features",
      "Iconography and graphic design",
    ],
  },
  {
    id: 6,
    buttonTitle: "Get Started",
    packageHeading: "Application UI/UX Design Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 3500,
    originalPrice: 7000,
    features: [
      "Design for the application’s main screen",
      "Up to 5 additional screens",
      "Custom layout and design elements, such as typography, color scheme, and graphics",
      "Custom iconography, graphic design, and branding",
      "Design for user interface (UI) elements, such as buttons, menus, and forms",
      "User experience (UX) design, including user flow diagrams and wireframes",
    ],
  },
  {
    id: 7,
    buttonTitle: "Get Started",
    packageHeading: "Advanced Application UI/UX Design Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 6500,
    originalPrice: 13000,
    features: [
      "Design for the application’s main screen",
      "Up to 10 additional screens",
      "More complex design elements, such as custom illustrations, animations, and interactive features",
      "Custom iconography, graphic design, and branding",
      "Design for user interface (UI) elements, such as buttons, menus, and forms",
      "User experience (UX) design, including user flow diagrams and wireframes",
      "Customized user research and user testing to optimize the design",
    ],
  },
  {
    id: 8,
    buttonTitle: "Get Started",
    packageHeading: "E-Commerce Application Design Package",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: 7500,
    originalPrice: 15000,
    features: [
      "Design for the application’s main screen, plus up to 20 additional screens",
      "Shopping cart design, product page design, and checkout process design",
      "Custom graphic design for promotional materials",
      "Custom iconography, graphic design, and branding",
      "Design for user interface (UI) elements, such as buttons, menus, and forms",
      "User experience (UX) design, including user flow diagrams and wireframes",
      "Customized user research and user testing to optimize the design",
    ],
  },
];

export const appPackages = [
  {
    id: 1,
    buttonTitle: "Get a quote",
    packageHeading: "Hybrid Application",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: null,
    originalPrice: null,
    features: ["Let’s Discuss"],
  },
  {
    id: 2,
    buttonTitle: "Get a quote",
    packageHeading: "IOS Application Development",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: null,
    originalPrice: null,
    features: ["Let’s Discuss"],
  },
  {
    id: 3,
    buttonTitle: "Get a quote",
    packageHeading: "Android Application",
    packageDescription: "Cost Effective Package for your business",
    currentPrice: null,
    originalPrice: null,
    features: ["Let’s Discuss"],
  },
];

export const hostingPackages = [
  {
    id: 1,
    buttonTitle: "Get Started",
    packageHeading: "Basic Hosting Package",
    packageDescription: "Affordable hosting solution for small websites",
    currentPrice: 500,
    originalPrice: 1000,
    features: [
      "1 Website",
      "10 GB SSD Storage",
      "100 GB Bandwidth",
      "Free SSL Certificate",
      "Standard Support",
    ],
  },
  {
    id: 2,
    buttonTitle: "Get Started",
    packageHeading: "Advanced Hosting Package",
    packageDescription: "Ideal for growing websites with moderate traffic",
    currentPrice: 1000,
    originalPrice: 2000,
    features: [
      "Up to 5 Websites",
      "50 GB SSD Storage",
      "500 GB Bandwidth",
      "Free SSL Certificate",
      "Daily Backups",
      "Priority Support",
    ],
  },
  {
    id: 3,
    buttonTitle: "Get Started",
    packageHeading: "E-Commerce Hosting Package",
    packageDescription: "Optimized for online stores and transactions",
    currentPrice: 2000,
    originalPrice: 4000,
    features: [
      "Unlimited Websites",
      "100 GB SSD Storage",
      "Unlimited Bandwidth",
      "Free SSL Certificate",
      "Daily Backups",
      "E-Commerce Optimization",
      "Advanced Security Features",
      "24/7 Priority Support",
    ],
  },
  {
    id: 4,
    buttonTitle: "Get Started",
    packageHeading: "VPS Hosting Package",
    packageDescription: "Powerful virtual server hosting for developers",
    currentPrice: 2500,
    originalPrice: 5000,
    features: [
      "2 vCPU Cores",
      "4 GB RAM",
      "80 GB SSD Storage",
      "Root Access",
      "Dedicated IP",
      "Free SSL Certificate",
      "Advanced Firewall",
      "Full Control Panel Access",
    ],
  },
  {
    id: 5,
    buttonTitle: "Get Started",
    packageHeading: "Managed WordPress Hosting",
    packageDescription: "Optimized WordPress hosting with full management",
    currentPrice: 1500,
    originalPrice: 3000,
    features: [
      "1-3 WordPress Sites",
      "30 GB SSD Storage",
      "Free SSL & CDN",
      "Automatic Updates",
      "Staging Environment",
      "Daily Backups",
      "Malware Scanning",
      "Expert WP Support",
    ],
  },
  {
    id: 6,
    buttonTitle: "Get Started",
    packageHeading: "Business Hosting Package",
    packageDescription: "High performance hosting for business-critical sites",
    currentPrice: 3000,
    originalPrice: 6000,
    features: [
      "Unlimited Websites",
      "200 GB SSD Storage",
      "Unlimited Bandwidth",
      "Free SSL & CDN",
      "Daily Backups",
      "Performance Optimization",
      "Advanced Security Suite",
      "24/7 VIP Support",
    ],
  },
  {
    id: 7,
    buttonTitle: "Get Started",
    packageHeading: "Cloud Hosting Package",
    packageDescription: "Scalable cloud infrastructure for growing businesses",
    currentPrice: 4000,
    originalPrice: 8000,
    features: [
      "Cloud-based Hosting",
      "Auto-Scaling Resources",
      "High Availability",
      "Free SSL & Global CDN",
      "Container Support (Docker, Kubernetes)",
      "Integrated Monitoring",
      "Multi-region Deployment",
      "Enterprise Support",
    ],
  },
  {
    id: 8,
    buttonTitle: "Get Started",
    packageHeading: "Enterprise Hosting Package",
    packageDescription: "Custom solutions for enterprise-scale applications",
    currentPrice: 8000,
    originalPrice: 16000,
    features: [
      "Custom Infrastructure Design",
      "Unlimited Storage & Bandwidth",
      "Load Balancing & Failover",
      "Dedicated Account Manager",
      "Custom Security Configurations",
      "Compliance Assistance (GDPR, HIPAA, etc.)",
      "24/7 Dedicated Support",
      "SLA-Backed Uptime Guarantee",
    ],
  },
];

export const pitchDeckPackages = [
  {
    id: 1,
    buttonTitle: "Get a quote",
    packageHeading: "Presentation Design",
    packageDescription: "Visually compelling presentations tailored to your brand.",
    currentPrice: null,
    originalPrice: null,
    features: ["Let’s Discuss"],
  },
  {
    id: 2,
    buttonTitle: "Get a quote",
    packageHeading: "Investment Deck Design",
    packageDescription: "High-impact decks designed to attract investors.",
    currentPrice: null,
    originalPrice: null,
    features: ["Let’s Discuss"],
  },
  {
    id: 3,
    buttonTitle: "Get a quote",
    packageHeading: "PowerPoint Presentation",
    packageDescription: "Custom PowerPoint decks for business or pitches.",
    currentPrice: null,
    originalPrice: null,
    features: ["Let’s Discuss"],
  },
  {
    id: 4,
    buttonTitle: "Get a quote",
    packageHeading: "Google Slide Presentation",
    packageDescription: "Professional presentations built in Google Slides.",
    currentPrice: null,
    originalPrice: null,
    features: ["Let’s Discuss"],
  },
];

